--- 
abstract: ~
author: Ash Berlin <ash@cpan.org>
build_requires: 
  FindBin: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-C3-Componentised
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::C3: 0
  Class::Inspector: 0
version: 1
